accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

events/urls.py
from django.urls import path
from . import views

app_name = 'event'
urlpatterns = [
    path('', views.EventListView.as_view(), name='list'),
    path('add', views.EventCreateView.as_view(), name='create'),
    path('edit/<int:pk>', views.EventUpdateView.as_view(), name='update'),
    path('event/<int:pk>', views.EventDetailView.as_view(), name='detail'),
    path('attend/<int:pk>', views.AttendanceView.as_view(), name='attend'),
]

sherpany/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from events.views import EventListView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('events.urls', namespace='event')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.utils.translation import ugettext_lazy as _


class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    """Custom User model using email instead of username """

    username = None
    email = models.EmailField(_('email address'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

events/models.py
from django.db import models
from accounts.models import User

class Event(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    date = models.DateField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __unicode__(self):
        return self.title

class Attendance(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    event = models.ForeignKey(
        Event, 
        on_delete=models.CASCADE, 
        related_name="attending"
    )

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from accounts.models import User

class CustomUserCreationForm(UserCreationForm):
    """ overriding UserCreationForm to support email instead of username """
    class Meta:
        model = User
        fields = ("email",)

accounts/views.py
from django.urls import reverse_lazy
from django.views import generic
from accounts.forms import CustomUserCreationForm

class SignUp(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

events/views.py
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.detail import DetailView
from django.views.generic.base import RedirectView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_list_or_404, get_object_or_404
from django.urls import reverse_lazy
from django.http import Http404

from datetime import datetime
from bootstrap_datepicker_plus import DatePickerInput
from events.models import Event, Attendance

class EventListView(ListView):
    queryset = Event.objects \
        .prefetch_related('attending') \
        .filter(date__gte=datetime.now()) \
        .order_by('-date')
    paginate_by = 20
    template_name = 'event_list.html'

class EventDetailView(LoginRequiredMixin, DetailView):
    model = Event
    template_name = 'event_detail.html'

    def get_context_data(self, **kwargs):
        context = super(EventDetailView, self).get_context_data(**kwargs)
        obj = self.get_object()
        # owners of the event should see the edit link
        if obj.user == self.request.user:
            context.update({'can_edit': True})
        # users already attending an event should not see the attend link
        if obj.attending.filter(user=self.request.user).exists():
            context.update({'already_attending': True})
        return context

class EventUpdateView(LoginRequiredMixin, UpdateView):
    model = Event
    fields = ['title', 'description', 'date']
    template_name = 'event_form.html'
    success_url = reverse_lazy('event:list')

    def dispatch(self, request, *args, **kwargs):
        """ Making sure that only authors can update events """
        if self.get_object().user != request.user:
            raise Http404
        return super(EventUpdateView, self).dispatch(request, *args, **kwargs)

class EventCreateView(LoginRequiredMixin, CreateView):
    """ authentication is required """
    model = Event
    fields = ['title', 'description', 'date']
    template_name = 'event_form.html'
    success_url = reverse_lazy('event:list')

    def get_form(self):
        """ override form to include date picker """
        form = super().get_form()
        form.fields['date'].widget = DatePickerInput()
        return form

    def form_valid(self, form):
        """ override form validation method to include current user """
        form.instance.user = self.request.user
        return super(EventCreateView, self).form_valid(form)

class AttendanceView(LoginRequiredMixin, RedirectView):
    url = reverse_lazy('event:list')

    def get_redirect_url(self, *args, **kwargs):
        event = get_object_or_404(Event, pk=kwargs.get('pk'))
        attendance, created = Attendance.objects.get_or_create(
            user=self.request.user,
            event=event
        )
        return super().get_redirect_url(*args, **kwargs)

events/templates/event_detail.html
{% extends 'base.html' %}
{% load tags %}
{% load bootstrap3 %}

{% block title %}Event{% endblock %}

{% block content %}
<h2>Event</h2>
<div class="row">
    <div class="col-md-6">{{ object.title }}</div>
    <div class="col-md-6 text-right">{{ object.date|date }}</div>
</div>
<div class="description">
    {{ object.description|linebreaks }}
</div>
{% if object.attending.count %}
<div class="row">
    <div class="col-md-12">
        <h3 class="attending">People attending event</h3>
        <ul class="list-inline">
        {% for attend in object.attending.all %}
            <li>{{ attend.user.email|convert_to_username }}</li>
        {% endfor %}
        </ul>
    </div>
</div>
{% endif %}
{% if not already_attending %}
  <div class="attend-link">
    <a href="{% url 'event:attend' pk=event.id %}">Attend this event</a>
  </div>
{% endif %}
{% endblock %}

events/templates/event_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}{% if object %}Edit{% else %}Add{% endif %} Event{% endblock %}

{% block content %}
<h2>{% if object %}Edit{% else %}Add{% endif %} Event</h2>
<form method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
    <button type="submit" class="btn btn-primary">
        {% if object %}Edit{% else %}Add{% endif %}
    </button>
</form>
{% endblock %}

events/templates/event_list.html
{% extends 'base.html' %}
{% load tags %}

{% block title %}Events{% endblock %}

{% block content %}

<h2>Events</h2>
{% if object_list %}
<table class="table">
  <tbody>
   {% for event in object_list %}
    <tr>
      <td>{{ event.date|date }}</td>
      <td>
        {% if request.user.is_authenticated %}
            <a href="{% url 'event:detail' pk=event.id %}">{{ event.title }}</a>
        {% else %}
            {{ event.title }}
        {% endif %}
      </td>
      <td>{{ event.user.email|convert_to_username }}</td>
      <td>{{ event.attending.count }} attending</td>
    </tr>
   {% endfor %}
  </tbody>
</table>

  {% if is_paginated %}
  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center pagination-sm">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="{% url 'event:list' %}?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1">Previous</a>
        </li>
        {% endif %} 
        {% for object in page_obj.paginator.page_range %}
        <li class="page-item">
            <a class="page-link" href="{% url 'event:list' %}?page={{ forloop.counter }}">{{ forloop.counter }}</a>
        </li>
        {% endfor %} 
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="{% url 'event:list' %}?page={{ page_obj.next_page_number }}">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#">Next</a>
        </li>
        {% endif %}
    </ul>
  </nav>
  {% endif %}

{% else %}
  No events yet
{% endif %}

{% endblock %}

templates/base.html
{% load bootstrap3 %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
  {% bootstrap_css %}
  <script src="//code.jquery.com/jquery.min.js"></script>
  {% bootstrap_javascript %}
  {{ form.media }}
  <meta charset="utf-8">
  <title>Sherpany Code Challenge :: {% block title %}{% endblock %}</title>
</head>
<body>

  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'event:list' %}">Sherpany Code Challenge</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
          {% if can_edit %}
            <li><a href="{% url 'event:update' pk=object.id %}">Edit Event</a></li>
          {% else %}
            <li><a href="{% url 'event:create' %}">Add Event</a></li>
          {% endif %}
          <li><a href="{% url 'logout' %}">Logout</a></li>
        {% else %}
          <li><a href="{% url 'login' %}">Login</a></li>
          <li><a href="{% url 'signup' %}">Signup</a></li>
        {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <main>
    <div class="container">
      <div class="row">
          {% bootstrap_messages %}
          <div class="col-md-5">
          {% block content %}{% endblock %}
          </div>
      </div>
    </div>
  </main>

</body>
</html>

templates/signup.html
{% extends 'base.html' %}

{% load bootstrap3 %}

{% block title %}Sign Up{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post" class="form">
    {% csrf_token %}
    {% for field in form %}
      {% bootstrap_field field show_help=False %}
    {% endfor %}
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{% endblock %}